
import java.awt.event.WindowEvent;
import java.sql.*;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Students_and_Teachers_Management extends javax.swing.JFrame {

    /**
     * Creates new form Students_and_Teachers_Management
     */
    
     
            
    Connection conn=null;
    ResultSet rs=null;
    PreparedStatement pst=null;
    
    public Students_and_Teachers_Management() {
        initComponents();
        
                
        conn=javaconnect.connerDb();
        CurrentDate();
    }
    
    
        
    public void CurrentDate() 
    {

        
        Thread clock=new Thread()
        {
            public void run()
            {
                for(;;)
                    
                {
                
      //  Calendar cal=new GregorianCalendar();
      //  int month=cal.get(Calendar.MONTH);
       // int year=cal.get(Calendar.YEAR);
        //int day=cal.get(Calendar.DAY_OF_MONTH);
        
       // date_txt.setText(day+"/"+(month+1)+"/"+(year));
        
        
        
        //int second=cal.get(Calendar.SECOND); 
        //int mint=cal.get(Calendar.MINUTE);
        //int hour=cal.get(Calendar.HOUR);
        //txt_time.setText(hour+":"+(mint)+":"+(second));  
        

                    
                   /* try {
                        sleep(1000);
                        
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Students_and_Teachers_Management.class.getName()).log(Level.SEVERE, null, ex);
                    }*/
                }
            }
        };
        
        
        
        //clock.start();
        
                
    }
    
        
    public  void close()
    {
        WindowEvent winClosingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txt_teachers = new javax.swing.JButton();
        txt_students = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txt_me = new javax.swing.JButton();
        txt_Employee = new javax.swing.JButton();
        txt_help = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        jLabel1.setText("jLabel1");

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("All Information");
        setResizable(false);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("School Management System");

        txt_teachers.setBackground(new java.awt.Color(255, 255, 255));
        txt_teachers.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_teachers.setForeground(new java.awt.Color(0, 51, 51));
        txt_teachers.setText("Teachers");
        txt_teachers.setToolTipText("Teachers Data Entry Option");
        txt_teachers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_teachersActionPerformed(evt);
            }
        });

        txt_students.setBackground(new java.awt.Color(255, 255, 255));
        txt_students.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_students.setForeground(new java.awt.Color(0, 51, 51));
        txt_students.setText("Students");
        txt_students.setToolTipText("Students Data Entry Option");
        txt_students.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_studentsActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.setToolTipText("Close The Window");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txt_me.setBackground(new java.awt.Color(255, 255, 255));
        txt_me.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt_me.setForeground(new java.awt.Color(51, 0, 51));
        txt_me.setText("About me");
        txt_me.setToolTipText("About me");
        txt_me.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_meActionPerformed(evt);
            }
        });

        txt_Employee.setBackground(new java.awt.Color(255, 255, 255));
        txt_Employee.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_Employee.setForeground(new java.awt.Color(51, 51, 51));
        txt_Employee.setText("Employees");
        txt_Employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_EmployeeActionPerformed(evt);
            }
        });

        txt_help.setBackground(new java.awt.Color(255, 255, 255));
        txt_help.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txt_help.setText("Help");
        txt_help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_helpActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("Teachers--------->");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("Students--------->");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel5.setText("Employees------>");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton4)
                        .addGap(248, 248, 248)
                        .addComponent(txt_help, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_me))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(jLabel3))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(141, 141, 141)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel4)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(133, 133, 133)
                                        .addComponent(txt_teachers))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(117, 117, 117)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txt_Employee)
                                            .addComponent(txt_students))))))
                        .addGap(100, 158, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(txt_me)
                    .addComponent(txt_help))
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_teachers)
                    .addComponent(jLabel2))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_students)
                    .addComponent(jLabel4))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Employee)
                    .addComponent(jLabel5))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_teachersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_teachersActionPerformed
        // TODO add your handling code here:
        

                Teachers_Information_System t = new Teachers_Information_System();
                t.setVisible(true);
                close();
    }//GEN-LAST:event_txt_teachersActionPerformed

    private void txt_studentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_studentsActionPerformed
        // TODO add your handling code here:
        
                 Students_Infromation_System s = new Students_Infromation_System();
                 s.setVisible(true);
                 close();
    }//GEN-LAST:event_txt_studentsActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txt_meActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_meActionPerformed
        // TODO add your handling code here:
        
                 My_Profile s = new My_Profile();
                 s.setVisible(true);
                 
        
    }//GEN-LAST:event_txt_meActionPerformed

    private void txt_EmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_EmployeeActionPerformed
        // TODO add your handling code here:
        
                
                 Employees_Infromation_System s = new Employees_Infromation_System();
                 s.setVisible(true);
                 close();
        
    }//GEN-LAST:event_txt_EmployeeActionPerformed

    private void txt_helpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_helpActionPerformed
        // TODO add your handling code here:
        
                 Help s = new Help();
                 s.setVisible(true);
                 close();
    }//GEN-LAST:event_txt_helpActionPerformed

 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton txt_Employee;
    private javax.swing.JButton txt_help;
    private javax.swing.JButton txt_me;
    private javax.swing.JButton txt_students;
    private javax.swing.JButton txt_teachers;
    // End of variables declaration//GEN-END:variables
}
